# Generated by Django 6.0.1 on 2026-01-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_post_created_at_alter_post_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                upload_to="posts_images/", verbose_name="Publlicación"
            ),
        ),
    ]
