# Generated by Django 6.0.1 on 2026-01-18 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_follow_userprofile_followers"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("follower", "following")},
        ),
    ]
